#dataSnapshot:
#  uploadedFiles:
#    path:
spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 20
        order_inserts: true
        generate_statistics: true
  h2:
    console:
      enabled: true